from __future__ import annotations  # PEP563 Forward References

from enum import StrEnum


class Protocol(StrEnum):
    PCIE = "PCIe"
    AHCI = "AHCI"
    UHCI = "UHCI"
    SAS = "SAS"
    SATA = "SATA"
    USB = "USB"
    NVME = "NVMe"
    FC = "FC"
    ISCSI = "iSCSI"
    FC_OE = "FCoE"
    FCP = "FCP"
    FICON = "FICON"
    NVME_OVER_FABRICS = "NVMeOverFabrics"
    SMB = "SMB"
    NF_SV3 = "NFSv3"
    NF_SV4 = "NFSv4"
    HTTP = "HTTP"
    HTTPS = "HTTPS"
    FTP = "FTP"
    SFTP = "SFTP"
    IWARP = "iWARP"
    RO_CE = "RoCE"
    RO_C_EV2 = "RoCEv2"
    I2C = "I2C"
    TCP = "TCP"
    UDP = "UDP"
    TFTP = "TFTP"
    GEN_Z = "GenZ"
    MULTI_PROTOCOL = "MultiProtocol"
    INFINI_BAND = "InfiniBand"
    ETHERNET = "Ethernet"
    NV_LINK = "NVLink"
    OEM = "OEM"
    DISPLAY_PORT = "DisplayPort"
    HDMI = "HDMI"
    VGA = "VGA"
    DVI = "DVI"
    CXL = "CXL"
    UPI = "UPI"
    QPI = "QPI"
    EMMC = "eMMC"
