from fastapi import FastAPI

from . import (
    acceleration_function,
    acceleration_function_collection,
    account_service,
    address_pool,
    address_pool_collection,
    aggregate,
    aggregate_collection,
    aggregation_service,
    aggregation_source,
    aggregation_source_collection,
    allow_deny,
    allow_deny_collection,
    application,
    application_collection,
    assembly,
    battery,
    battery_collection,
    battery_metrics,
    bios,
    boot_option,
    boot_option_collection,
    cable,
    cable_collection,
    certificate,
    certificate_collection,
    certificate_locations,
    certificate_service,
    chassis,
    chassis_collection,
    circuit,
    circuit_collection,
    component_integrity,
    component_integrity_collection,
    composition_reservation,
    composition_reservation_collection,
    composition_service,
    computer_system,
    computer_system_collection,
    connection,
    connection_collection,
    connection_method,
    connection_method_collection,
    container,
    container_collection,
    container_image,
    container_image_collection,
    control,
    control_collection,
    coolant_connector,
    coolant_connector_collection,
    cooling_loop,
    cooling_loop_collection,
    cooling_unit,
    cooling_unit_collection,
    cxl_logical_device,
    cxl_logical_device_collection,
    drive,
    drive_collection,
    drive_metrics,
    endpoint,
    endpoint_collection,
    endpoint_group,
    endpoint_group_collection,
    environment_metrics,
    ethernet_interface,
    ethernet_interface_collection,
    event_destination,
    event_destination_collection,
    event_service,
    external_account_provider,
    external_account_provider_collection,
    fabric,
    fabric_adapter,
    fabric_adapter_collection,
    fabric_collection,
    facility,
    facility_collection,
    fan,
    fan_collection,
    filter,
    filter_collection,
    graphics_controller,
    graphics_controller_collection,
    heater,
    heater_collection,
    heater_metrics,
    host_interface,
    host_interface_collection,
    job,
    job_collection,
    job_service,
    json_schema_file,
    json_schema_file_collection,
    key,
    key_collection,
    key_policy,
    key_policy_collection,
    key_service,
    leak_detection,
    leak_detector,
    leak_detector_collection,
    license,
    license_collection,
    license_service,
    log_entry,
    log_entry_collection,
    log_service,
    log_service_collection,
    manager,
    manager_account,
    manager_account_collection,
    manager_collection,
    manager_diagnostic_data,
    manager_network_protocol,
    media_controller,
    media_controller_collection,
    memory,
    memory_chunks,
    memory_chunks_collection,
    memory_collection,
    memory_domain,
    memory_domain_collection,
    memory_metrics,
    memory_region,
    memory_region_collection,
    message_registry_file,
    message_registry_file_collection,
    metric_definition,
    metric_definition_collection,
    metric_report,
    metric_report_collection,
    metric_report_definition,
    metric_report_definition_collection,
    network_adapter,
    network_adapter_collection,
    network_adapter_metrics,
    network_device_function,
    network_device_function_collection,
    network_device_function_metrics,
    network_interface,
    network_interface_collection,
    network_port,
    network_port_collection,
    operating_config,
    operating_config_collection,
    operating_system,
    outbound_connection,
    outbound_connection_collection,
    outlet,
    outlet_collection,
    outlet_group,
    outlet_group_collection,
    pcie_device,
    pcie_device_collection,
    pcie_function,
    pcie_function_collection,
    pcie_slots,
    port,
    port_collection,
    port_metrics,
    power,
    power_distribution,
    power_distribution_collection,
    power_distribution_metrics,
    power_domain,
    power_domain_collection,
    power_equipment,
    power_subsystem,
    power_supply,
    power_supply_collection,
    power_supply_metrics,
    processor,
    processor_collection,
    processor_metrics,
    pump,
    pump_collection,
    registered_client,
    registered_client_collection,
    reservoir,
    reservoir_collection,
    resource_block,
    resource_block_collection,
    role,
    role_collection,
    route_entry,
    route_entry_collection,
    route_set_entry,
    route_set_entry_collection,
    secure_boot,
    secure_boot_database,
    secure_boot_database_collection,
    security_policy,
    sensor,
    sensor_collection,
    serial_interface,
    serial_interface_collection,
    service_conditions,
    service_root,
    session,
    session_collection,
    session_service,
    signature,
    signature_collection,
    simple_storage,
    simple_storage_collection,
    software_inventory,
    software_inventory_collection,
    storage,
    storage_collection,
    storage_controller,
    storage_controller_collection,
    storage_controller_metrics,
    switch,
    switch_collection,
    switch_metrics,
    task,
    task_collection,
    task_service,
    telemetry_service,
    thermal,
    thermal_equipment,
    thermal_metrics,
    thermal_subsystem,
    triggers,
    triggers_collection,
    trusted_component,
    trusted_component_collection,
    update_service,
    usb_controller,
    usb_controller_collection,
    vcat_entry,
    vcat_entry_collection,
    virtual_media,
    virtual_media_collection,
    vlan_network_interface,
    vlan_network_interface_collection,
    volume,
    volume_collection,
    zone,
    zone_collection,
)


def include_router(app: FastAPI) -> None:
    app.include_router(acceleration_function.router)
    app.include_router(acceleration_function_collection.router)
    app.include_router(account_service.router)
    app.include_router(address_pool.router)
    app.include_router(address_pool_collection.router)
    app.include_router(aggregate.router)
    app.include_router(aggregate_collection.router)
    app.include_router(aggregation_service.router)
    app.include_router(aggregation_source.router)
    app.include_router(aggregation_source_collection.router)
    app.include_router(allow_deny.router)
    app.include_router(allow_deny_collection.router)
    app.include_router(application.router)
    app.include_router(application_collection.router)
    app.include_router(assembly.router)
    app.include_router(battery.router)
    app.include_router(battery_collection.router)
    app.include_router(battery_metrics.router)
    app.include_router(bios.router)
    app.include_router(boot_option.router)
    app.include_router(boot_option_collection.router)
    app.include_router(cable.router)
    app.include_router(cable_collection.router)
    app.include_router(certificate.router)
    app.include_router(certificate_collection.router)
    app.include_router(certificate_locations.router)
    app.include_router(certificate_service.router)
    app.include_router(chassis.router)
    app.include_router(chassis_collection.router)
    app.include_router(circuit.router)
    app.include_router(circuit_collection.router)
    app.include_router(component_integrity.router)
    app.include_router(component_integrity_collection.router)
    app.include_router(composition_reservation.router)
    app.include_router(composition_reservation_collection.router)
    app.include_router(composition_service.router)
    app.include_router(computer_system.router)
    app.include_router(computer_system_collection.router)
    app.include_router(connection.router)
    app.include_router(connection_collection.router)
    app.include_router(connection_method.router)
    app.include_router(connection_method_collection.router)
    app.include_router(container.router)
    app.include_router(container_collection.router)
    app.include_router(container_image.router)
    app.include_router(container_image_collection.router)
    app.include_router(control.router)
    app.include_router(control_collection.router)
    app.include_router(coolant_connector.router)
    app.include_router(coolant_connector_collection.router)
    app.include_router(cooling_loop.router)
    app.include_router(cooling_loop_collection.router)
    app.include_router(cooling_unit.router)
    app.include_router(cooling_unit_collection.router)
    app.include_router(cxl_logical_device.router)
    app.include_router(cxl_logical_device_collection.router)
    app.include_router(drive.router)
    app.include_router(drive_collection.router)
    app.include_router(drive_metrics.router)
    app.include_router(endpoint.router)
    app.include_router(endpoint_collection.router)
    app.include_router(endpoint_group.router)
    app.include_router(endpoint_group_collection.router)
    app.include_router(environment_metrics.router)
    app.include_router(ethernet_interface.router)
    app.include_router(ethernet_interface_collection.router)
    app.include_router(event_destination.router)
    app.include_router(event_destination_collection.router)
    app.include_router(event_service.router)
    app.include_router(external_account_provider.router)
    app.include_router(external_account_provider_collection.router)
    app.include_router(fabric.router)
    app.include_router(fabric_adapter.router)
    app.include_router(fabric_adapter_collection.router)
    app.include_router(fabric_collection.router)
    app.include_router(facility.router)
    app.include_router(facility_collection.router)
    app.include_router(fan.router)
    app.include_router(fan_collection.router)
    app.include_router(filter.router)
    app.include_router(filter_collection.router)
    app.include_router(graphics_controller.router)
    app.include_router(graphics_controller_collection.router)
    app.include_router(heater.router)
    app.include_router(heater_collection.router)
    app.include_router(heater_metrics.router)
    app.include_router(host_interface.router)
    app.include_router(host_interface_collection.router)
    app.include_router(job.router)
    app.include_router(job_collection.router)
    app.include_router(job_service.router)
    app.include_router(json_schema_file.router)
    app.include_router(json_schema_file_collection.router)
    app.include_router(key.router)
    app.include_router(key_collection.router)
    app.include_router(key_policy.router)
    app.include_router(key_policy_collection.router)
    app.include_router(key_service.router)
    app.include_router(leak_detection.router)
    app.include_router(leak_detector.router)
    app.include_router(leak_detector_collection.router)
    app.include_router(license.router)
    app.include_router(license_collection.router)
    app.include_router(license_service.router)
    app.include_router(log_entry.router)
    app.include_router(log_entry_collection.router)
    app.include_router(log_service.router)
    app.include_router(log_service_collection.router)
    app.include_router(manager.router)
    app.include_router(manager_account.router)
    app.include_router(manager_account_collection.router)
    app.include_router(manager_collection.router)
    app.include_router(manager_diagnostic_data.router)
    app.include_router(manager_network_protocol.router)
    app.include_router(media_controller.router)
    app.include_router(media_controller_collection.router)
    app.include_router(memory.router)
    app.include_router(memory_chunks.router)
    app.include_router(memory_chunks_collection.router)
    app.include_router(memory_collection.router)
    app.include_router(memory_domain.router)
    app.include_router(memory_domain_collection.router)
    app.include_router(memory_metrics.router)
    app.include_router(memory_region.router)
    app.include_router(memory_region_collection.router)
    app.include_router(message_registry_file.router)
    app.include_router(message_registry_file_collection.router)
    app.include_router(metric_definition.router)
    app.include_router(metric_definition_collection.router)
    app.include_router(metric_report.router)
    app.include_router(metric_report_collection.router)
    app.include_router(metric_report_definition.router)
    app.include_router(metric_report_definition_collection.router)
    app.include_router(network_adapter.router)
    app.include_router(network_adapter_collection.router)
    app.include_router(network_adapter_metrics.router)
    app.include_router(network_device_function.router)
    app.include_router(network_device_function_collection.router)
    app.include_router(network_device_function_metrics.router)
    app.include_router(network_interface.router)
    app.include_router(network_interface_collection.router)
    app.include_router(network_port.router)
    app.include_router(network_port_collection.router)
    app.include_router(operating_config.router)
    app.include_router(operating_config_collection.router)
    app.include_router(operating_system.router)
    app.include_router(outbound_connection.router)
    app.include_router(outbound_connection_collection.router)
    app.include_router(outlet.router)
    app.include_router(outlet_collection.router)
    app.include_router(outlet_group.router)
    app.include_router(outlet_group_collection.router)
    app.include_router(pcie_device.router)
    app.include_router(pcie_device_collection.router)
    app.include_router(pcie_function.router)
    app.include_router(pcie_function_collection.router)
    app.include_router(pcie_slots.router)
    app.include_router(port.router)
    app.include_router(port_collection.router)
    app.include_router(port_metrics.router)
    app.include_router(power.router)
    app.include_router(power_distribution.router)
    app.include_router(power_distribution_collection.router)
    app.include_router(power_distribution_metrics.router)
    app.include_router(power_domain.router)
    app.include_router(power_domain_collection.router)
    app.include_router(power_equipment.router)
    app.include_router(power_subsystem.router)
    app.include_router(power_supply.router)
    app.include_router(power_supply_collection.router)
    app.include_router(power_supply_metrics.router)
    app.include_router(processor.router)
    app.include_router(processor_collection.router)
    app.include_router(processor_metrics.router)
    app.include_router(pump.router)
    app.include_router(pump_collection.router)
    app.include_router(registered_client.router)
    app.include_router(registered_client_collection.router)
    app.include_router(reservoir.router)
    app.include_router(reservoir_collection.router)
    app.include_router(resource_block.router)
    app.include_router(resource_block_collection.router)
    app.include_router(role.router)
    app.include_router(role_collection.router)
    app.include_router(route_entry.router)
    app.include_router(route_entry_collection.router)
    app.include_router(route_set_entry.router)
    app.include_router(route_set_entry_collection.router)
    app.include_router(secure_boot.router)
    app.include_router(secure_boot_database.router)
    app.include_router(secure_boot_database_collection.router)
    app.include_router(security_policy.router)
    app.include_router(sensor.router)
    app.include_router(sensor_collection.router)
    app.include_router(serial_interface.router)
    app.include_router(serial_interface_collection.router)
    app.include_router(service_conditions.router)
    app.include_router(service_root.router)
    app.include_router(session.router)
    app.include_router(session_collection.router)
    app.include_router(session_service.router)
    app.include_router(signature.router)
    app.include_router(signature_collection.router)
    app.include_router(simple_storage.router)
    app.include_router(simple_storage_collection.router)
    app.include_router(software_inventory.router)
    app.include_router(software_inventory_collection.router)
    app.include_router(storage.router)
    app.include_router(storage_collection.router)
    app.include_router(storage_controller.router)
    app.include_router(storage_controller_collection.router)
    app.include_router(storage_controller_metrics.router)
    app.include_router(switch.router)
    app.include_router(switch_collection.router)
    app.include_router(switch_metrics.router)
    app.include_router(task.router)
    app.include_router(task_collection.router)
    app.include_router(task_service.router)
    app.include_router(telemetry_service.router)
    app.include_router(thermal.router)
    app.include_router(thermal_equipment.router)
    app.include_router(thermal_metrics.router)
    app.include_router(thermal_subsystem.router)
    app.include_router(triggers.router)
    app.include_router(triggers_collection.router)
    app.include_router(trusted_component.router)
    app.include_router(trusted_component_collection.router)
    app.include_router(update_service.router)
    app.include_router(usb_controller.router)
    app.include_router(usb_controller_collection.router)
    app.include_router(vcat_entry.router)
    app.include_router(vcat_entry_collection.router)
    app.include_router(virtual_media.router)
    app.include_router(virtual_media_collection.router)
    app.include_router(vlan_network_interface.router)
    app.include_router(vlan_network_interface_collection.router)
    app.include_router(volume.router)
    app.include_router(volume_collection.router)
    app.include_router(zone.router)
    app.include_router(zone_collection.router)
